In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration = 1
min_exploration = 0.01
exploration_decay_rate = 0.001

In [4]:
reward_all_episode = []

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
             action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state,reward,done,info = env.step(action)
        ## bellman equation
        q_table[state,action] = q_table[state,action]*(1-learning_rate) + learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
        ## new_q_value        =              old_q_value                +             learned_Value

        ## learned_value = reward + discount * maximum_future_reward
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break
    exploration_rate = min_exploration + (max_exploration-min_exploration)*np.exp(-exploration_decay_rate*episode)
    reward_all_episode.append(rewards_current_episode)

rewards_per_thosand_episode = np.split(np.array(reward_all_episode),num_episodes/1000)
count = 1000
print("average reward per thousand episodes")
for r in rewards_per_thosand_episode:
    print(count,":",str(sum(r/1000)))
    count += 1000

average reward per thousand episodes
1000 : 0.048000000000000036
2000 : 0.21000000000000016
3000 : 0.4090000000000003
4000 : 0.5640000000000004
5000 : 0.6610000000000005
6000 : 0.6840000000000005
7000 : 0.6830000000000005
8000 : 0.6690000000000005
9000 : 0.6830000000000005
10000 : 0.6780000000000005


In [5]:
print("\n\n_____Q-table______\n")
print(q_table)



_____Q-table______

[[0.49818669 0.47936071 0.47698893 0.46724047]
 [0.28501847 0.35503982 0.26316444 0.45884631]
 [0.38410106 0.42083675 0.36585155 0.44079499]
 [0.22989985 0.25696199 0.24469667 0.42883518]
 [0.51350744 0.42967944 0.41405821 0.41691798]
 [0.         0.         0.         0.        ]
 [0.30554234 0.12148767 0.16527969 0.13279913]
 [0.         0.         0.         0.        ]
 [0.407112   0.44253845 0.41667371 0.54392541]
 [0.37205166 0.57175615 0.4549835  0.3693395 ]
 [0.46619889 0.42403895 0.38213566 0.33201974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.40666186 0.52473504 0.73557002 0.57093831]
 [0.74502713 0.86386414 0.7412584  0.78848813]
 [0.         0.         0.         0.        ]]


In [6]:


for episode in range(3):
    state = env.reset()
    done = False
    print("episode number",episode)
    time.sleep(1)
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        clear_output(True)
        env.render()
        time.sleep(.25)
    
        action = np.argmax(q_table[state,:])
        new_state,reward,done,info = env.step(action)
        if done == True:
            clear_output(True)
            if reward == 1:
                print("you reach the goal")
            else:
                print("you lose or you in the hole")
            break
        state = new_state

you lose or you in the hole
